services:
  - type: web
    name: siddu-potadar-jewelry
    env: node
    buildCommand: "cd client && npm install --include=dev && npm run build && cd ../server && npm install && rm -rf ./dist && cp -r ../client/dist ./dist"
    startCommand: "cd server && node src/db/seed.js && npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.15.1
      - key: JWT_SECRET
        generateValue: true
